a = input('Digita algo:')
print('O tipo primitivo desse valor éa', type(a))
print('Só te m espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizado?', a.istitle())